### ISSUE TITLE
`godolint --version` returns non-zero exit code

### ISSUE THREAD

**Issue by patrickhoefler** [zabio3/godolint#32]
## Description

When executing `godolint --version`, the command correctly outputs its version but exits with a status code of 1. However, it should exit with a status code of 0, indicating successful execution.

## Steps to Reproduce

1. Run `godolint --version; echo $?`
2. Observe the printed exit status.

## Expected Behavior

The `godolint --version` command should print its version and exit with a status code of 0.

## Actual Behavior

The command prints:
```
godolint version 0.1.4
```
But the exit status is `1`.

## Additional Context

- Version: `godolint 0.1.4`
- OS: macOS 13.5.2

**Comment by zabio3** [comment]
@patrickhoefler 

Thank you for bringing this to our attention 😄 

I'm pleased to inform you that we have addressed this issue in the latest update. The godolint --version command should now correctly exit with a status code of 0, reflecting a successful execution. This change is part of the new release, version 0.1.5, which is now available for download.

```bash
godolint --version; echo $?  
godolint version 0.1.5
0
```
