### ISSUE TITLE
Incorrect version information for v1.0.0

### ISSUE THREAD

**Issue by patrickhoefler** [zabio3/godolint#38]
**Description:**
When downloading `godolint` version 1.0.0, checking the version using `./godolint -v` shows an unexpected result:

```
godolint version 0.1.5
```

**Steps to Reproduce:**
1. Download and install `godolint` version 1.0.0.
2. Check the version using the command `./godolint -v`.

**Expected Behavior:**
Expecting `godolint` to display version 1.0.0.

**Actual Behavior:**
The tool incorrectly displays version 0.1.5.

**Additional Information:**
- macOS Version: 14.1.1

**Comment by zabio3** [comment]
@patrickhoefler 

Certainly, here's a concise response:

Thank you for pointing out the version issue with godolint 1.0.0. We've fixed it and updated to version 1.0.1. Please download the latest version 👍 


```bash
godolint --version; echo $?  
godolint version 1.0.1
0
```
